/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ClaimManager } from "./ClaimManager";

export { ClaimManager__factory } from "./factories/ClaimManager__factory";
